name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: new name 2
        run: go test ./... -cover

  style:


    steps:
      -name : what is check check is priating your code
      use: actions/checkout@v4
      -name: use go code
      use:actions/setup-go@v5

      -name:maingame
      run: test -z $(go fmt ./...)

